[build-system]
requires = ["setuptools", "setuptools_scm[toml]", "wheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "BeamMe"
description = "BeamMe: A general purpose 3D beam finite element input generator"
requires-python = ">=3.11"
authors = [{name = "BeamMe Authors"}]
maintainers = [
  {name = "Ivo Steinbrecher", email = "ivo.steinbrecher@unibw.de"},
  {name = "David Rudlstorfer", email = "david.rudlstorfer@tum.de"},
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
  "autograd",
  "geomdl",
  "ipykernel",
  "jupytext",
  "notebook",
  "numpy",
  "numpy-quaternion",
  "pyvista[jupyter]",
  "scipy",
  "splinepy",
  "vedo==2024.5.2", # Needed as a fix for the splinepy visualization tool gustaf
  "vtk"
]

dynamic = ["version"]

[tool.setuptools_scm]
version_file = "src/beamme/version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"

[project.optional-dependencies]
cubitpy = [
  "cubitpy>=0.2.2",
  "netCDF4"
]
fourc = ["fourcipp"]
dev = [
  "beamme[cubitpy]",
  "beamme[fourc]",
  "coverage",
  "genbadge[coverage]",
  "pdoc",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "testbook",
  "vistools>=0.7.1",
  "xmltodict"
]

[project.urls]
Homepage = "https://beamme-py.github.io/beamme/"
Documentation = "https://beamme-py.github.io/beamme/api-documentation/"
Repository = "https://github.com/beamme-py/beamme/"
Issues = "https://github.com/beamme-py/beamme/issues/"

# Tools

[tool.coverage.run]
omit = [
  "src/beamme/version.py",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-p pytest_cov --cov-report=term --cov-report=html --cov-report=xml --cov-fail-under=90 --cov=src/beamme/"
markers = [
  "fourc: tests in combination with 4C",
  "arborx: tests in combination with ArborX",
  "coreform: tests in combination with Coreform Cubit",
  "performance: performance tests"
]
filterwarnings = [
  # Ignore warnings coming from CubitPy, as they are only related to testing scripts
  # and not directly to BeamMe code.
  "ignore::cubitpy.conf.CubitPyWarning",
]
